<?php

/**
* Trait UserTrait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;
    use Illuminate\Database\Eloquent\SoftDeletes;

trait UserTrait
{
            use SoftDeletes;
    
    protected $table = 'users';

    protected $fillable = [
                    'id',
                    'name',
                    'email',
                    'email_verified_at',
                    'password',
                    'created_at',
                    'updated_at',
                    'deleted_at',
            ];
    }
